"""T0: hash-pinned research environment (ANALYSIS_SPEC_STAGE_B.md).

Usage, from the repository root with CPython 3.12.4:
  py -3.12 research/frontier_replay_20261001/t0_env.py lock   # wheelhouse -> t0_requirements.lock
  py -3.12 research/frontier_replay_20261001/t0_env.py build  # fresh venv, verify, write receipt
"""

import hashlib
import json
import platform
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
WHEELHOUSE = ROOT / ".context" / "frontier_t0_wheelhouse"
ENV = ROOT / ".context" / "frontier_t0_env"
LOCK = HERE / "t0_requirements.lock"
OUT = ROOT / "results" / "frontier_replay_20261001"
RECEIPT = OUT / "t0_environment.json"
SPEC = "manuscript/advantage-frontier-2026-09-23/ANALYSIS_SPEC_STAGE_B.md"
IMPORTS = ["numba", "numpy", "scipy", "mpmath", "matplotlib", "pytest", "markdown", "qiskit",
           "numba.cuda"]

SMOKE = r"""
import json, numpy as np
from numba import cuda
out = dict(available=cuda.is_available())
if out["available"]:
    dev = cuda.get_current_device()
    out.update(name=dev.name.decode() if isinstance(dev.name, bytes) else str(dev.name),
               compute_capability=list(dev.compute_capability))
    @cuda.jit
    def add(a, b, c):
        i = cuda.grid(1)
        if i < c.size:
            c[i] = a[i] + b[i]
    a = np.arange(1 << 20, dtype=np.float64); b = 0.5 * a; c = np.zeros_like(a)
    add[(a.size + 255) // 256, 256](a, b, c)
    out["kernel_matches_numpy"] = bool(np.array_equal(c, a + b))
print(json.dumps(out))
"""


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def canon(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def run(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


def lock():
    lines = ["# Generated by t0_env.py lock from PyPI wheels; install with --require-hashes."]
    for whl in sorted(WHEELHOUSE.glob("*.whl"), key=lambda p: canon(p.name.split("-")[0])):
        name, version = whl.name.split("-")[:2]
        lines.append(f"{canon(name)}=={version} \\\n    --hash=sha256:{sha256(whl)}")
    LOCK.write_text("\n".join(lines) + "\n")
    print("wrote", LOCK, len(lines) - 1, "wheels")


def locked():
    return dict(re.findall(r"^([a-z0-9-]+)==(\S+)", LOCK.read_text(), re.M))


def tool_version(cmd):
    try:
        r = run(cmd)
        return (r.stdout or r.stderr).strip().splitlines()[0] if r.returncode == 0 else None
    except OSError:
        return None


def build():
    if ENV.exists() or RECEIPT.exists():
        raise SystemExit(f"refusing to reuse {ENV} or overwrite {RECEIPT}")
    OUT.mkdir(parents=True, exist_ok=True)
    subprocess.run([sys.executable, "-m", "venv", str(ENV)], check=True)
    py = str(ENV / "Scripts" / "python.exe")
    install = run([py, "-m", "pip", "install", "--no-index", "--find-links", str(WHEELHOUSE),
                   "--require-hashes", "--no-deps", "-r", str(LOCK)])
    check = run([py, "-m", "pip", "check"])
    listing = json.loads(run([py, "-m", "pip", "list", "--format=json"]).stdout)
    installed = {canon(p["name"]): p["version"] for p in listing if canon(p["name"]) != "pip"}
    imports = {m: run([py, "-c", f"import {m}"]).returncode == 0 for m in IMPORTS}
    smoke = run([py, "-c", SMOKE])
    gpu = run(["nvidia-smi", "--query-gpu=name,driver_version,memory.total",
               "--format=csv,noheader"])
    cpu = run(["powershell", "-NoProfile", "-Command",
               "(Get-CimInstance Win32_Processor).Name"])
    receipt = dict(
        spec=SPEC,
        spec_sha256=sha256(ROOT / SPEC),
        lock_sha256=sha256(LOCK),
        interpreter=run([py, "-c", "import sys; print(sys.version)"]).stdout.strip(),
        base_interpreter=sys.executable,
        install_returncode=install.returncode,
        install_stderr_tail=install.stderr.strip().splitlines()[-5:],
        pip_check=dict(returncode=check.returncode, output=check.stdout.strip()),
        installed=installed,
        installed_equals_lock=installed == locked(),
        imports=imports,
        cuda_smoke=dict(returncode=smoke.returncode,
                        result=json.loads(smoke.stdout) if smoke.returncode == 0 else None,
                        stderr_tail=smoke.stderr.strip().splitlines()[-8:]),
        gpu=gpu.stdout.strip() or None,
        cpu=cpu.stdout.strip() or None,
        power_plan=tool_version(["powercfg", "/getactivescheme"]),
        platform=platform.platform(),
        miktex=tool_version(["miktex", "--version"]),
        pdflatex=tool_version(["pdflatex", "--version"]),
        latexmk=tool_version(["latexmk", "--version"]),
    )
    receipt["t0_passed"] = (install.returncode == 0 and check.returncode == 0
                            and receipt["installed_equals_lock"] and all(imports.values()))
    RECEIPT.write_text(json.dumps(receipt, indent=1) + "\n")
    print(json.dumps({k: receipt[k] for k in ("t0_passed", "installed_equals_lock", "imports",
                                              "pip_check", "cuda_smoke")}, indent=1))


if __name__ == "__main__":
    {"lock": lock, "build": build}[sys.argv[1]]()
